### ISSUE TITLE
Possible memory leake in watch mode?

### ISSUE THREAD

**Issue by LightGuard** [jbake-org/jbake-maven-plugin#42]
Using version 0.3.6-rc.2 (I assume this is the latest?) and 2.7.0-rc.2 for core, I only get a few (three to five) rebuilds before things crap out and won't generate any more. I haven't done enough testing to know exactly what is going on, but I'm happy to submit a repo for testing.

**Comment by jonbullock** [comment]
Yeah 0.3.6-rc.2 is the latest release and a repo for testing would be great thanks.

**Comment by LightGuard** [comment]
https://github.com/LightGuard/kie-proj-head-foot-testing/tree/jbake

**Comment by jonbullock** [comment]
Thanks for supplying that repo.

Can I just double check you're using the `jbake:watch` Maven goal when process craps out on you?

I'm trying locally on Linux using OpenJDK 11 and an error is thrown after the first re-build for me and then the watching of file system changes stops all together. Is this the same error you're getting?

```
[INFO] Refreshing
Exception in thread "Thread-6" java.lang.IllegalStateException: Queue full
	at java.base/java.util.AbstractQueue.add(AbstractQueue.java:98)
	at java.base/java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:326)
	at org.jbake.maven.util.DirWatcher.onUpdated(DirWatcher.java:57)
	at org.jbake.maven.util.DirWatcher.access$000(DirWatcher.java:17)
	at org.jbake.maven.util.DirWatcher$1.onFileChange(DirWatcher.java:40)
	at org.apache.commons.io.monitor.FileAlterationObserver.doMatch(FileAlterationObserver.java:410)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:333)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:334)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:334)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:334)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:334)
	at org.apache.commons.io.monitor.FileAlterationObserver.checkAndNotify(FileAlterationObserver.java:303)
	at org.apache.commons.io.monitor.FileAlterationMonitor.run(FileAlterationMonitor.java:183)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by LightGuard** [comment]
Yep, I was using that command. I think I needed to go down to Java 8 as well. I don't recall if I was getting an error on Java 11.
